language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "if [[ $DJANGO_VERSION == 'dev' ]]; then pip install git+https://github.com/django/django.git#egg=Django; else pip install Django==$DJANGO_VERSION; fi"
  - pip install "git+https://github.com/MichalMaM/ella.git#egg=ella"
  - pip install -r dev_requirements.txt
  - python setup.py develop
env:
  - DJANGO_VERSION="1.8.5"
  - DJANGO_VERSION="1.9.2"
  - DJANGO_VERSION="1.10"
script: python setup.py test
